import React from "react";
import { HashRouter as Router, Routes, Route, Navigate } from "react-router-dom";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "sonner";
import { AuthProvider, useAuth } from "./contexts/AuthContext";
import { LoginPage } from "./components/LoginPage";
import { DashboardLayout } from "./components/DashboardLayout";
import { Dashboard } from "./components/Dashboard";
import { PatientManagement } from "./components/PatientManagement";
import { PatientProfile } from "./components/PatientProfile";
import { FoodDatabase } from "./components/FoodDatabase";
import { DietPlans } from "./components/DietPlans";
import { Reports } from "./components/Reports";
import { Settings } from "./components/Settings";
import  AuthButtons  from "./components/AuthButtons";
// Doctor-specific components
import { Collections } from "./components/Collections";
import { Recipes } from "./components/Recipes";
import { DietChart } from "./components/DietChart";
import { AutoGenerateDiet } from "./components/AutoGenerateDiet";
import { ChatWithPatients } from "./components/ChatWithPatients";
// Patient-specific components
import { DietHistory } from "./components/DietHistory";
import { ChatWithDoctor } from "./components/ChatWithDoctor";
import { Reminders } from "./components/Reminders";
import { PatientSettings } from "./components/PatientSettings";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000,
      retry: 1,
    },
  },
});

type ErrorBoundaryState = { hasError: boolean };

class ErrorBoundary extends React.Component<React.PropsWithChildren<{}>, ErrorBoundaryState> {
  constructor(props: React.PropsWithChildren<{}>) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(/*error: any*/) {
    return { hasError: true };
  }

  componentDidCatch(error: any, errorInfo: any) {
    // send to logging service if desired
    console.error("Error caught by boundary:", error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen bg-background flex items-center justify-center p-4">
          <div className="text-center">
            <h1 className="text-2xl text-foreground mb-4">Something went wrong</h1>
            <p className="text-muted-foreground mb-4">Please refresh the page to try again</p>
            <button
              onClick={() => window.location.reload()}
              className="px-4 py-2 bg-primary text-primary-foreground rounded-md"
            >
              Refresh Page
            </button>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}

function AppContent() {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4" />
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return <LoginPage />;
  }

  return (
    <ErrorBoundary>
      <Router>
        <DashboardLayout>
          <Routes>
            <Route path="/" element={<Navigate to="/dashboard" replace />} />
            <Route path="/dashboard" element={<Dashboard />} />

            {/* Doctor-only routes */}
            <Route path="/patients" element={<PatientManagement />} />
            <Route path="/patients/:id" element={<PatientProfile />} />
            <Route path="/collections" element={<Collections />} />
            <Route path="/recipes" element={<Recipes />} />
            <Route path="/diet-chart" element={<DietChart />} />
            <Route path="/auto-generate" element={<AutoGenerateDiet />} />
            <Route path="/food-database" element={<FoodDatabase />} />
            <Route path="/chat-doctor" element={<ChatWithPatients />} />

            {/* Patient-only routes */}
            <Route path="/diet-history" element={<DietHistory />} />
            <Route path="/chat" element={<ChatWithDoctor />} />
            <Route path="/reminders" element={<Reminders />} />

            {/* Common routes */}
            <Route path="/reports" element={<Reports />} />
            <Route path="/settings" element={<Settings />} />
            <Route path="/patient-settings" element={<PatientSettings />} />

            <Route path="*" element={<Navigate to="/dashboard" replace />} />
          </Routes>
        </DashboardLayout>
      </Router>
    </ErrorBoundary>
  );
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <div>
          <header style={{ padding: 12, borderBottom: "1px solid #eee" }}>
            <h1 style={{ margin: 0 }}>Ayurvedic Diet Management App</h1>
            <div style={{ marginTop: 8 }}>
              <AuthButtons />
            </div>
          </header>
          <main>
            <AppContent />
          </main>
          <Toaster position="top-right" />
        </div>
      </AuthProvider>
    </QueryClientProvider>
  );
}
